name: topo_client
version: 1.0.3
description: Manipulate TopoJSON, such as to merge shapes, and convert it back to GeoJSON.
repository: https://github.com/luizbarboza/topo_client

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  topo_parse: ^1.0.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.0
